services:
  db:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: find-a-friend
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local